version: '3'
services:
  web:
    build: .
    image: php-composer
    container_name: tema7
    ports:
      - "80:80"
    volumes:
      - .:/app
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"